name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: [ dotnet ]

    steps:
    - uses: actions/checkout@v2

    - name: Restore dependencies
      run: dotnet restore
      
    - name: Publish
      run: dotnet publish
